# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ec0b38e88f6d8634822d4119d96da09dfbb184908f31f67a7878ecc2524b4f3ddc80600aae35e6232dc3b5ffd1afa7d255c2f4859d21c2407c2f70ae471db2f

test:
  secret_key_base: 477c574b49470c1548215cf2bf9981477ca32bd875e6d7cb3fede11a334f96809d76841c5db711215bc156590651547b9efb36ced8fd050fadc1dfaf05c61add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
