# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ef18269565c179209bcee8207beb8973b3b2519acc9162022e4d12a8e32c9e0093d7b95452125580ec7b0e02838793e37ab563dec8005e8d5069a6c891146f5

test:
  secret_key_base: b18bbe12c48b30f93d688dee5bc9c3f947f36b98830a706aae1f260d4ebc9e8f8c98381c1f765f0c74255ab83aa5fe20bf1f9971afc8c24dfb4b30e22aaabee0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
